import datetime as dt
import matplotlib.pyplot as plt
from matplotlib import style
import pandas as pd
import pandas_datareader.data as web

style.use('ggplot')

# the additional parameters "parse the dates" and index the first column (the dates column) for us; without
# these parameters a new index is autogenerated:

# pandas can read from almost any database! it's documentation is really good. use it.

df = pd.read_csv('tsla.csv', parse_dates = True, index_col = 0)

#print(df.head())
print(df[['open','close']].head())

df['close'].plot()
plt.show()
